### ISSUE TITLE
Using YAML + Markdown format in documentation comments

### ISSUE THREAD

**Issue by souvikdc9** [dotnet/csharplang#878]
# Using YAML + Markdown format in documentation comments

## Summary
Our current style of doumentation comment using XML is too verbose.
We can achieve a cleaner approach using YAML + Markdown similar to OpenAPI specification.

## Design
Here is an small example of a YAML based documentation comment.

```yaml
summary:      A summary of the member.
description:  A description of the member. Markdown syntax may be used for rich text representation.
returns:      A description of the returned value.
parameters:
  - name: a
    description:  A description of the parameter.
  - name: b
    description:  A description of the parameter.
```

Along with moving from XML to YAML, we may also consider the /** */ comment style instead of using triple slash per line.

The above approach looks cleaner than using the verbose XML start and end tags.
However, with the above approach, we may increase the number of lines than its XML counterpart.
This may not be a problem, as most IDEs keep the doc comments collapsed by default.
Or, we can find a more compact YAML structure.

Using YAML + Markdown can also be a advantage for docfx, which uses YAML as its input.

Below is an detailed example of using all the documentation comment tags into a YAML + Markdown format.

```yaml
summary:      A summary of the member.
description:  A description of the member. Markdown syntax may be used for rich text representation.
returns:      A description of the returned value.

parameters:
  - name: a
    description:  A description of the parameter.
    throws:
      - ArgumentNullException
      - ArgumentOutOfRangeException
  - name: b
    description:  A description of the parameter.
    throws:
      - ArgumentNullException
      - ArgumentOutOfRangeException

type parameters:
  - name: T
    description:  A description of the type parameter.
  - name: U
    description:  A description of the type parameter.

throws:
  ArgumentNullException:
    description:  A reason of the exception that can be thrown by the member.
  ArgumentOutOfRangeException:
    description:  A reason of the exception that can be thrown by the member.

remarks: |
A long remarks regarding the member.
Markdown syntax may be used for rich text representation.
With code examples like
``cs
var result = DoSomething(a, b);
``

example: |
``cs
var result = DoSomething(a, b);
var tranformed = DoSomethingMore(result);
Console.WriteLine(tranformed);
``

see:
  - OverloadedDoSomething(type, type)
  - OverloadedDoSomething(type, type)
  - MyAnotherClass
```

## Drawbacks
- Older IDE's will not support the newer format. For this, we can generate an XML doc side by side.
- YAML format may also increase the count of lines than its XML counterpart.

**Comment by HaloFour** [comment]
The C# design team could chase the stylistic preferences for documentation all day long and not satisfy everyone.

In my opinion as the language already has one inline documentation format it doesn't need another one, particularly one where the name means "yet another" and represents another markup language du jour.  I particularly don't like that YAML is whitespace sensitive, making it paradigmically different from the language it intends to document.  You have to learn different syntax just to manage that whitespace sensitivity, such as when a long value is broken up over multiple lines, which is common in XML documentation.  Inline tags, also common, also have an awkward syntax.  YAML being a superset of JSON basically means baking two additional languages into the spec.

**Comment by yaakov-h** [comment]
You say that xmldoc is "too verbose", but then acknowledge that your proposal "may increase the number of lines".

What problem does this actually solve?

**Comment by souvikdc9** [comment]
XML is no-doubt verbose. But, migrating to stricter YAML standard sometimes increase the count of lines.
For, e.g., in the below code `params` can be defined in two lines in XML, whereas my proposal YAML requires 3 extra lines.

With XML,
```cs
/// <summary>Encrypts an input byte array and returns the encrypted array.</summary>
/// <param name="key">The session key to use for the encryption.</param>
/// <param name="data">The data to encrypt.</param>
/// <returns>A byte array that contains the encrypted data.</returns>
/// <exception cref="ArgumentNullException"><paramref name="data"/> is null.</exception>
/// <exception cref="InvalidOperationException">The session key has expired.</exception>
public byte[] Encrypt(byte[] key, byte[] data) { }
```

With YAML,
```cs
/**
summary: Encrypts an input byte array and returns the encrypted array
returns: A byte array that contains the encrypted data.
parameters:
  - name: key
    description:  The session key to use for the encryption.
  - name: data
    description:  The data to encrypt.
throws:
  ArgumentNullException:
    description:  `data` is null.
  InvalidOperationException:
    description:  The session key has expired.
*/
public byte[] Encrypt(byte[] key, byte[] data) { }
```

We can find a more compact YAML structure, build a custom C#FM structure, or keep in that way.
But in the long run migrating to YAML + Markdown far outweighs the current XML style.

For, e.g., we can also define the parameter tag in this way. But this loses the advantage of adding additional info to a parameter.
```yaml
parameters:
  key: The session key to use for the encryption.
  data: The data to encrypt.
```

Let's take another example to see why XML is not fit for documentating.

With XML,
```cs
/// <summary>Encrypts an input byte array and returns the encrypted array</summary>
/// <remarks>
///   <para>
///     The encryption internally uses the ECB mode for encryption.
///     The data that is to be provided must conform to the defined specification.
///   </para>
///   <para>
///     When using the encryption few points needs to be remembered.
///   <para>
///   <list type="bullet">  
///     <item>  
///       <description>The key size must be 256 in size.</description>  
///     </item>
///     <item>
///       <description> The data must be base64 encoded.</description>  
///     </item>
///   </list>
/// </remarks>
public byte[] Encrypt(byte[] key, byte[] data) { }
```

With YAML + Markdown,
```cs
/**
summary:  Encrypts an input byte array and returns the encrypted array.

remarks: |
The encryption internally uses the ECB mode for encryption.
The data that is to be provided must conform to the defined specification.

When using the encryption few points needs to be remembered.
- The key size must be 256 in size.
- The data must be base64 encoded.
*/
public byte[] Encrypt(byte[] key, byte[] data) { }
```

We can see from the above example, how YAML can benefit over XML.
Someone could try typing the whole comment block in the current version of VS Code.
Also take into consideration the numerous `<see/>` tag that we use in a good descriptive doc comment.

We can also add few more tags with minimal no. characters to the YAML format like, `author`, `version`, `contributors`, `complexity`. And Latex!
Moreover, directly writing markdown in code can be very much helpful to the documentation pipeline from code to website generation.

As about stylistic preferences and "yet another", comments play an integral part of coding.
Any changes made to the way we comment directly affects the way we write and read C# code.
As about learing, with our current style, we still have to lookup the `Recommended Tags for Documentation Comments` many a times just to write `remarks` and `example`.
We read comments more directly over code, and lesser through websites. Reading a machine-centric XML doesn't go with beautiful and elegant human-centric C# code.

Regards,
Souvik
